#!/bin/bash

# Setear variables del script
script_dir="$(dirname "$(realpath "$0")")"
destination_dir="${script_dir}/cva6_files"
cva6_repo_dir="${script_dir}/cva6"
hpdcache_dir="${script_dir}/cva6/core/cache_subsystem/hpdcache"
target_cfg="cv64a6_mmu"
bad_include='include "common_cells/registers.svh"'
good_include='include "registers.svh"'

# Crea carpeta de destino `cva6_files`
mkdir -p "$destination_dir"

# Copiar cada uno de los archivos y carpetas del micro CVA6 en la carpeta `cva6_files`
cp -r "${cva6_repo_dir}/core/include/" "${destination_dir}"
mv "${destination_dir}/include" "${destination_dir}/core_include"
rm ${destination_dir}/core_include/cv*
cp -r "${cva6_repo_dir}/vendor/pulp-platform/common_cells/include/" "${destination_dir}"
mv "${destination_dir}/include" "${destination_dir}/common_cells_include"
cp -r "${cva6_repo_dir}/vendor/pulp-platform/common_cells/src/" "${destination_dir}"
mv "${destination_dir}/src" "${destination_dir}/common_cells_src"
rm -rf "${destination_dir}/common_cells_src/deprecated"
cp -r "${cva6_repo_dir}/vendor/pulp-platform/axi/include/" "${destination_dir}"
mv "${destination_dir}/include" "${destination_dir}/axi_include"
cp -r "${cva6_repo_dir}/common/local/util/" "${destination_dir}"
mv "${destination_dir}/util" "${destination_dir}/common_local_util"
cp -r "${hpdcache_dir}/rtl/include" "${destination_dir}"
mv "${destination_dir}/include" "${destination_dir}/hpdcache_include"
cp "${cva6_repo_dir}/core/include/cvxif_types.svh" "${destination_dir}"
cp "${cva6_repo_dir}/vendor/pulp-platform/fpga-support/rtl/SyncDpRam.sv" "${destination_dir}"
cp "${cva6_repo_dir}/vendor/pulp-platform/fpga-support/rtl/AsyncDpRam.sv" "${destination_dir}"
cp "${cva6_repo_dir}/vendor/pulp-platform/fpga-support/rtl/AsyncThreePortRam.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cvfpu/src/fpnew_pkg.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cvfpu/src/fpnew_cast_multi.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cvfpu/src/fpnew_classifier.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cvfpu/src/fpnew_divsqrt_multi.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cvfpu/src/fpnew_fma_multi.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cvfpu/src/fpnew_fma.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cvfpu/src/fpnew_noncomp.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cvfpu/src/fpnew_opgroup_block.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cvfpu/src/fpnew_opgroup_fmt_slice.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cvfpu/src/fpnew_opgroup_multifmt_slice.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cvfpu/src/fpnew_rounding.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cvfpu/src/fpnew_top.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/control_mvp.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/div_sqrt_top_mvp.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/iteration_div_sqrt_mvp.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/norm_div_sqrt_mvp.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/nrbd_nrsc_mvp.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/preprocess_mvp.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/include/config_pkg.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/include/${target_cfg}_config_pkg.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/include/riscv_pkg.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/include/ariane_pkg.sv" "${destination_dir}"
cp "${cva6_repo_dir}/vendor/pulp-platform/axi/src/axi_pkg.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/include/wt_cache_pkg.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/include/std_cache_pkg.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/include/instr_tracer_pkg.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/include/build_config_pkg.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cvxif_compressed_if_driver.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cvxif_issue_register_commit_if_driver.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cvxif_example/include/cvxif_instr_pkg.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cvxif_fu.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cvxif_example/cvxif_example_coprocessor.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cvxif_example/instr_decoder.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cvxif_example/compressed_instr_decoder.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cvxif_example/copro_alu.sv" "${destination_dir}"
cp "${cva6_repo_dir}/vendor/pulp-platform/common_cells/src/cf_math_pkg.sv" "${destination_dir}"
cp "${cva6_repo_dir}/vendor/pulp-platform/common_cells/src/fifo_v3.sv" "${destination_dir}"
cp "${cva6_repo_dir}/vendor/pulp-platform/common_cells/src/lfsr.sv" "${destination_dir}"
cp "${cva6_repo_dir}/vendor/pulp-platform/common_cells/src/lfsr_8bit.sv" "${destination_dir}"
cp "${cva6_repo_dir}/vendor/pulp-platform/common_cells/src/stream_arbiter.sv" "${destination_dir}"
cp "${cva6_repo_dir}/vendor/pulp-platform/common_cells/src/stream_arbiter_flushable.sv" "${destination_dir}"
cp "${cva6_repo_dir}/vendor/pulp-platform/common_cells/src/stream_mux.sv" "${destination_dir}"
cp "${cva6_repo_dir}/vendor/pulp-platform/common_cells/src/stream_demux.sv" "${destination_dir}"
cp "${cva6_repo_dir}/vendor/pulp-platform/common_cells/src/lzc.sv" "${destination_dir}"
cp "${cva6_repo_dir}/vendor/pulp-platform/common_cells/src/rr_arb_tree.sv" "${destination_dir}"
cp "${cva6_repo_dir}/vendor/pulp-platform/common_cells/src/shift_reg.sv" "${destination_dir}"
cp "${cva6_repo_dir}/vendor/pulp-platform/common_cells/src/unread.sv" "${destination_dir}"
cp "${cva6_repo_dir}/vendor/pulp-platform/common_cells/src/popcount.sv" "${destination_dir}"
cp "${cva6_repo_dir}/vendor/pulp-platform/common_cells/src/exp_backoff.sv" "${destination_dir}"
cp "${cva6_repo_dir}/vendor/pulp-platform/common_cells/src/counter.sv" "${destination_dir}"
cp "${cva6_repo_dir}/vendor/pulp-platform/common_cells/src/delta_counter.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cva6.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cva6_rvfi_probes.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/alu.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/fpu_wrap.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/branch_unit.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/compressed_decoder.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/macro_decoder.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/controller.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/csr_buffer.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/csr_regfile.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/decoder.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/ex_stage.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/instr_realign.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/id_stage.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/issue_read_operands.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/issue_stage.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/load_unit.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/load_store_unit.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/lsu_bypass.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/mult.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/multiplier.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/serdiv.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/perf_counters.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/ariane_regfile_ff.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/ariane_regfile_fpga.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/scoreboard.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/store_buffer.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/amo_buffer.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/store_unit.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/commit_stage.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/axi_shim.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cva6_accel_first_pass_decoder_stub.sv" "${destination_dir}" 
cp "${cva6_repo_dir}/core/acc_dispatcher.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cva6_fifo_v3.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/frontend/btb.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/frontend/bht.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/frontend/ras.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/frontend/instr_scan.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/frontend/instr_queue.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/frontend/frontend.sv" "${destination_dir}" 
cp "${cva6_repo_dir}/core/cache_subsystem/wt_dcache_ctrl.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cache_subsystem/wt_dcache_mem.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cache_subsystem/wt_dcache_missunit.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cache_subsystem/wt_dcache_wbuffer.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cache_subsystem/wt_dcache.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cache_subsystem/cva6_icache.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cache_subsystem/wt_cache_subsystem.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cache_subsystem/wt_axi_adapter.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cache_subsystem/tag_cmp.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cache_subsystem/axi_adapter.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cache_subsystem/miss_handler.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cache_subsystem/cache_ctrl.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cache_subsystem/cva6_icache_axi_wrapper.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cache_subsystem/std_cache_subsystem.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cache_subsystem/std_nbdcache.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cache_subsystem/cva6_hpdcache_subsystem.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cache_subsystem/cva6_hpdcache_subsystem_axi_arbiter.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cache_subsystem/cva6_hpdcache_if_adapter.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cache_subsystem/cva6_hpdcache_wrapper.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cva6_mmu/cva6_mmu.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cva6_mmu/cva6_ptw.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cva6_mmu/cva6_tlb.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/cva6_mmu/cva6_shared_tlb.sv" "${destination_dir}"
cp "${cva6_repo_dir}/common/local/util/instr_tracer.sv" "${destination_dir}"
cp "${cva6_repo_dir}/common/local/util/tc_sram_wrapper.sv" "${destination_dir}"
cp "${cva6_repo_dir}/common/local/util/tc_sram_wrapper_cache_techno.sv" "${destination_dir}"
cp "${cva6_repo_dir}/vendor/pulp-platform/tech_cells_generic/src/rtl/tc_sram.sv" "${destination_dir}"
cp "${cva6_repo_dir}/common/local/util/sram.sv" "${destination_dir}"
cp "${cva6_repo_dir}/common/local/util/sram_cache.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/pmp/src/pmp.sv" "${destination_dir}"
cp "${cva6_repo_dir}/core/pmp/src/pmp_entry.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/utils/hpdcache_mem_req_read_arbiter.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/utils/hpdcache_mem_req_write_arbiter.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/utils/hpdcache_mem_resp_demux.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/utils/hpdcache_mem_to_axi_read.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/utils/hpdcache_mem_to_axi_write.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/common/macros/behav/hpdcache_sram_1rw.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/common/macros/behav/hpdcache_sram_wbyteenable_1rw.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/common/macros/behav/hpdcache_sram_wmask_1rw.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/hpdcache_pkg.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/common/hpdcache_demux.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/common/hpdcache_lfsr.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/common/hpdcache_sync_buffer.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/common/hpdcache_fifo_reg.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/common/hpdcache_fifo_reg_initialized.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/common/hpdcache_fxarb.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/common/hpdcache_rrarb.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/common/hpdcache_mux.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/common/hpdcache_1hot_to_binary.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/common/hpdcache_prio_1hot_encoder.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/common/hpdcache_sram.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/common/hpdcache_sram_wbyteenable.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/common/hpdcache_sram_wmask.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/common/hpdcache_regbank_wbyteenable_1rw.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/common/hpdcache_regbank_wmask_1rw.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/common/hpdcache_data_downsize.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/common/hpdcache_data_upsize.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/hwpf_stride/hwpf_stride_pkg.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/hwpf_stride/hwpf_stride.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/hwpf_stride/hwpf_stride_arb.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/hwpf_stride/hwpf_stride_wrapper.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/hpdcache.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/hpdcache_amo.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/hpdcache_cmo.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/hpdcache_core_arbiter.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/hpdcache_ctrl.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/hpdcache_ctrl_pe.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/hpdcache_memctrl.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/hpdcache_miss_handler.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/hpdcache_mshr.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/hpdcache_plru.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/hpdcache_rtab.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/hpdcache_uncached.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/hpdcache_victim_sel.sv" "${destination_dir}"
cp "${hpdcache_dir}/rtl/src/hpdcache_wbuf.sv" "${destination_dir}"

# Modificar archivos con typos
sed -i "s#${bad_include}#${good_include}#" "${destination_dir}/fpnew_fma.sv"
sed -i "s#${bad_include}#${good_include}#" "${destination_dir}/acc_dispatcher.sv"
sed -i "s#${bad_include}#${good_include}#" "${destination_dir}/fpnew_cast_multi.sv"
sed -i "s#${bad_include}#${good_include}#" "${destination_dir}/fpnew_fma_multi.sv"
sed -i "s#${bad_include}#${good_include}#" "${destination_dir}/fpnew_divsqrt_multi.sv"
sed -i "s#${bad_include}#${good_include}#" "${destination_dir}/fpnew_opgroup_multifmt_slice.sv"
sed -i "s#${bad_include}#${good_include}#" "${destination_dir}/fpnew_noncomp.sv"
sed -i "s#${bad_include}#${good_include}#" "${destination_dir}/common_cells_src/cdc_fifo_gray.sv"
sed -i "s#${bad_include}#${good_include}#" "${destination_dir}/common_cells_src/stream_to_mem.sv"
sed -i "s#${bad_include}#${good_include}#" "${destination_dir}/common_cells_src/isochronous_spill_register.sv"
sed -i "s#${bad_include}#${good_include}#" "${destination_dir}/common_cells_src/isochronous_4phase_handshake.sv"